[site]
title = "Live Life Real"
subtitle = "Sentences on faith, life, and code."
domain = "https://blog.calebely.net"
date_format = "%B %d, %Y"

[site.logo]
file = "logo.svg"
width = 80
height = 80
alt_text = ""

[site.nav]
podcast = { label = "Podcast", url = "https://podcast.calebely.net" }
portfolio = { label = "Portfolio", url = "https://calebely.net" }

[site.pages]
# Uncomment to create a distinct home page
# home_template = "index.jinja2"
404_template = "404.jinja2"

[directories]
theme = "/var/www/obsidian/site-theme"
static = "/var/www/obsidian/site-theme/static"
media = "/var/www/obsidian/attachments"
posts = "/var/www/obsidian/published"
output_dir = "dist"

[post]
# TODO Remove `index_template`
index_template = "index.jinja2"
post_index_template = "index.jinja2"
post_template = "post.jinja2"
output_dir = "post"

[post.defaults]
subtitle = ""
author = "Caleb"

# Fill this in to provide default tags. Can be `str` or `list[str]`
# tags = ""

# true: place default tags before post specific (default if not set)
# false: place default tags after post specific
# tags_before = true
