[site]
title = "Live Life Real"
subtitle = ""
domain = "https://blog.codetri.net"
date_format = "%B %d, %Y @ %I:%M %p %Z"

[site.logo]
file = "favicon.png"
width = 80
height = 80
alt_text = ""

[site.nav]
podcast = { label = "Podcast", url = "https://podcast.codetri.net/" }
portfolio = { label = "Portfolio", url = "https://codetri.net"}

[directories]
output = "dist"
posts = "post"
