[site]
title = "Live Life Real"
subtitle = "Sentences on faith, life, and code."
domain = "https://notes.calebely.net"
date_format = "%B %d, %Y"

[site.logo]
file = "logo.svg"
width = 80
height = 80
alt_text = ""

[site.nav]
podcast = { label = "Podcast", url = "https://podcast.calebely.net/" }
portfolio = { label = "Portfolio", url = "https://calebely.net" }

[directories]
theme = "usr/templates"
static = "usr/static"
posts = "/var/www/obsidian/published"
output = "dist"
post_output_base_slug = "post"
